export const LOAD_USER = ' LOAD_USER ';
export const POST_SIGN_UP = 'POST_SIGN_UP';
export const POST_SIGN_UP_FAIL = 'POST_SIGN_UP_FAIL';
export const LOGIN_SUCCESS = ' LOGIN_SUCCESS';
export const LOAD_USER_FAIL = ' LOAD_USER_FAIL ';
export const LOGIN_FAIL = ' LOGIN_FAIL';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const LOG_OUT = 'LOG_OUT';
